<?php

namespace SisUserBundle\Repository;

/**
 * Users1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Users1Repository extends \Doctrine\ORM\EntityRepository
{
}
